/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as TrainersRouteImport } from './routes/trainers'
import { Route as BlogsIndexRouteImport } from './routes/blogs.index'
import { Route as BlogsBlogIdRouteImport } from './routes/blogs.$blogId'
import { Route as BlogsManageRouteImport } from './routes/blogs.manage'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsLocationRouteImport } from './routes/locations.$location'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesServiceRouteImport } from './routes/services.$service'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainersRoute = TrainersRouteImport.update({
  id: '/trainers',
  path: '/trainers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsBlogIdRoute = BlogsBlogIdRouteImport.update({
  id: '/blogs/$blogId',
  path: '/blogs/$blogId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsManageRoute = BlogsManageRouteImport.update({
  id: '/blogs/manage',
  path: '/blogs/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationRoute = LocationsLocationRouteImport.update({
  id: '/locations/$location',
  path: '/locations/$location',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceRoute = ServicesServiceRouteImport.update({
  id: '/services/$service',
  path: '/services/$service',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/trainers': typeof TrainersRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs/manage': typeof BlogsManageRoute
  '/locations/$location': typeof LocationsLocationRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blogs/': typeof BlogsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/trainers': typeof TrainersRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs/manage': typeof BlogsManageRoute
  '/locations/$location': typeof LocationsLocationRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blogs': typeof BlogsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/trainers': typeof TrainersRoute
  '/blogs/$blogId': typeof BlogsBlogIdRoute
  '/blogs/manage': typeof BlogsManageRoute
  '/locations/$location': typeof LocationsLocationRoute
  '/services/$service': typeof ServicesServiceRoute
  '/blogs/': typeof BlogsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/trainers'
    | '/blogs/$blogId'
    | '/blogs/manage'
    | '/locations/$location'
    | '/services/$service'
    | '/blogs/'
    | '/locations/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/trainers'
    | '/blogs/$blogId'
    | '/blogs/manage'
    | '/locations/$location'
    | '/services/$service'
    | '/blogs'
    | '/locations'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/trainers'
    | '/blogs/$blogId'
    | '/blogs/manage'
    | '/locations/$location'
    | '/services/$service'
    | '/blogs/'
    | '/locations/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  TrainersRoute: typeof TrainersRoute
  BlogsBlogIdRoute: typeof BlogsBlogIdRoute
  BlogsManageRoute: typeof BlogsManageRoute
  LocationsLocationRoute: typeof LocationsLocationRoute
  ServicesServiceRoute: typeof ServicesServiceRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trainers': {
      id: '/trainers'
      path: '/trainers'
      fullPath: '/trainers'
      preLoaderRoute: typeof TrainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$blogId': {
      id: '/blogs/$blogId'
      path: '/blogs/$blogId'
      fullPath: '/blogs/$blogId'
      preLoaderRoute: typeof BlogsBlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/manage': {
      id: '/blogs/manage'
      path: '/blogs/manage'
      fullPath: '/blogs/manage'
      preLoaderRoute: typeof BlogsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$location': {
      id: '/locations/$location'
      path: '/locations/$location'
      fullPath: '/locations/$location'
      preLoaderRoute: typeof LocationsLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$service': {
      id: '/services/$service'
      path: '/services/$service'
      fullPath: '/services/$service'
      preLoaderRoute: typeof ServicesServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  TrainersRoute: TrainersRoute,
  BlogsBlogIdRoute: BlogsBlogIdRoute,
  BlogsManageRoute: BlogsManageRoute,
  LocationsLocationRoute: LocationsLocationRoute,
  ServicesServiceRoute: ServicesServiceRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
